services:
  webapp:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "186:186"
    environment:
      - ASPNETCORE_URLS=http://+:186
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    networks:
      - sids_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp
    networks:
      - sids_network
    restart: unless-stopped

networks:
  sids_network:
    driver: bridge